# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import surge_monitor_pb2 as surge__monitor__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in surge_monitor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PressureSensorServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamPressureData = channel.stream_unary(
                '/surge_monitor.PressureSensorService/StreamPressureData',
                request_serializer=surge__monitor__pb2.PressureDataBatch.SerializeToString,
                response_deserializer=surge__monitor__pb2.StreamAck.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/surge_monitor.PressureSensorService/GetStatus',
                request_serializer=surge__monitor__pb2.StatusRequest.SerializeToString,
                response_deserializer=surge__monitor__pb2.SystemStatus.FromString,
                _registered_method=True)


class PressureSensorServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamPressureData(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PressureSensorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamPressureData': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamPressureData,
                    request_deserializer=surge__monitor__pb2.PressureDataBatch.FromString,
                    response_serializer=surge__monitor__pb2.StreamAck.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=surge__monitor__pb2.StatusRequest.FromString,
                    response_serializer=surge__monitor__pb2.SystemStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'surge_monitor.PressureSensorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('surge_monitor.PressureSensorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PressureSensorService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamPressureData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/surge_monitor.PressureSensorService/StreamPressureData',
            surge__monitor__pb2.PressureDataBatch.SerializeToString,
            surge__monitor__pb2.StreamAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/surge_monitor.PressureSensorService/GetStatus',
            surge__monitor__pb2.StatusRequest.SerializeToString,
            surge__monitor__pb2.SystemStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
