# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: surge_monitor.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'surge_monitor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13surge_monitor.proto\x12\rsurge_monitor\"k\n\x11PressureDataBatch\x12\x11\n\tsensor_id\x18\x01 \x01(\r\x12\x16\n\x0etimestamp_base\x18\x02 \x01(\x01\x12\x16\n\x0esample_rate_hz\x18\x03 \x01(\r\x12\x13\n\x07samples\x18\x04 \x03(\x02\x42\x02\x10\x01\"F\n\tStreamAck\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x16\n\x0ereceived_count\x18\x02 \x01(\r\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x0f\n\rStatusRequest\"y\n\x0cSystemStatus\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x1e\n\x16\x62uffer_utilization_pct\x18\x02 \x01(\r\x12\x18\n\x10latest_timestamp\x18\x03 \x01(\x01\x12\x1e\n\x16total_samples_received\x18\x04 \x01(\r2\xb3\x01\n\x15PressureSensorService\x12R\n\x12StreamPressureData\x12 .surge_monitor.PressureDataBatch\x1a\x18.surge_monitor.StreamAck(\x01\x12\x46\n\tGetStatus\x12\x1c.surge_monitor.StatusRequest\x1a\x1b.surge_monitor.SystemStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'surge_monitor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRESSUREDATABATCH'].fields_by_name['samples']._loaded_options = None
  _globals['_PRESSUREDATABATCH'].fields_by_name['samples']._serialized_options = b'\020\001'
  _globals['_PRESSUREDATABATCH']._serialized_start=38
  _globals['_PRESSUREDATABATCH']._serialized_end=145
  _globals['_STREAMACK']._serialized_start=147
  _globals['_STREAMACK']._serialized_end=217
  _globals['_STATUSREQUEST']._serialized_start=219
  _globals['_STATUSREQUEST']._serialized_end=234
  _globals['_SYSTEMSTATUS']._serialized_start=236
  _globals['_SYSTEMSTATUS']._serialized_end=357
  _globals['_PRESSURESENSORSERVICE']._serialized_start=360
  _globals['_PRESSURESENSORSERVICE']._serialized_end=539
# @@protoc_insertion_point(module_scope)
